// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Infrastructure.Entity.MOVIMENTO_MANUAL", b =>
                {
                    b.Property<int>("DAT_MES")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("COD_COSIF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_PRODUTO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_USUARIO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DAT_ANO")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DAT_MOVIMENTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("DES_DESCRICAO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NUM_LANCAMENTO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VAL_VALOR")
                        .HasColumnType("INTEGER");

                    b.HasKey("DAT_MES");

                    b.ToTable("mOVIMENTO_MANUAL");
                });

            modelBuilder.Entity("Infrastructure.Entity.PRODUTO", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("DES_PRODUTO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("pRODUTO");
                });

            modelBuilder.Entity("Infrastructure.Entity.PRODUTO_COSIF", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_COST")
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_CLASSIFICACAO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("COD_PRODUTO", "COD_COST");

                    b.ToTable("pRODUTO_COSIF");
                });
#pragma warning restore 612, 618
        }
    }
}
